### ISSUE TITLE
App Web

### ISSUE THREAD

**Issue by iLc0** [ValentinGot/real-debrid#1]
Est-ce que tu as une petite appli web pour montrer comment ça fonctionne? Je suis très intéressé par la partie torrent :)

**Comment by ValentinGot** [comment]
Salut,

Non désolé je n'ai aucune appli qui l'utilise, mais ce n'est pas bien compliqué à utiliser.
En gros tu as a juste à faire :

```
// Login
// Le login utilise des cookies pour te garder connecter
// La reconnexion ce fait automatiquement une fois que le cookie est expiré
$user = new \RealDebrid\User();
$user->login('username', 'password');

// Ajout d'un torrent (seulement via magnet link)
$torrent = new \RealDebrid\Torrent();
$torrent->add('magnet:xxxxxx');
// 50GB correspond au champ splitting size
$torrent->add('magnet:xwxxxx', 50);
// Tu as le choix entre 3 hosters
// $HOSTER_UPTOBOX: Uptobox
// $HOSTER_1FICHIER: 1fichier
// $HOSTER_MEGA: Mega
$torrent->add('magnet:xwxxxx', 50, \RealDebrid\Torrent::$HOSTER_UPTOBOX);

// Récupération de la liste des torrents
// Ca te donne un JSON avec quasiement les même champs que le tableau sur Real-Debrid
$status = $torrent->status();
var_dump($status);
```

Voilà en esperant que ça t'aide =)

**Comment by iLc0** [comment]
Tu peux me dire ce que t'utilises comme API pour les torrents?

J'arrive à me connecter : https://real- debrid.fr/ajax/login.php?user=ABCDE&pass=ABCDE
J'arrive à débrider : https://real- debrid.fr/ajax/unrestrict.php?link=http://uptobox.com/ABCDE&remote=1

Mais j'arrive pas à lui envoyer un torrent à partir d'un magnet link ou d'un fichier .torrent

**Comment by ValentinGot** [comment]
Tu utilise pas mon API ? Les classes sont là pour ça ^^

Mais bon, pour te répondre, à partir d'un fichier torrent je ne l'ai pas fait.

Par contre pour un magnet link, tu dois passer en **POST** sur l'URL **https://real- debrid.fr/torrents**.
Changer le **Content-Type** en **multipart/form-data**
Et envoyer les params suivants :
- magnet: ton lien
- splitting_size: la taille en gb
- hoster: l'hôte sur lequel uploader
